export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_USER: "SET_USER",
  SET_CURRENT_PLAYLIST: "SET_CURRENT_PLAYLIST",
  SET_CURRENT_TRACK: " SET_CURRENT_TRACK",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
};
